### ISSUE TITLE
What's the data sources for the result 5.1 QAOA performance？

### ISSUE THREAD

**Issue by fgmn** [VicentePerezSoloviev/QAOA_BNSL_IBM#1]
I'm interested in your work that appies QAOA to BNs' structure learning. Next I'd like to recreate some of your work, but it seems that the paper doesn't mention the source of data for the result 5.1 QAOA performance. Looking forward to your reply!

**Comment by VicentePerezSoloviev** [comment]
Hi. Thank you for your interest in the work. If you mean the real application you can find the data in the .txt files. You will have to load them as are the precomputed scores for the BN learning
